name: Tests

on:
  workflow_dispatch:

jobs:
  nvcc-windows:
    runs-on: windows-latest
    name: "Python 3.12.7 / NVCC (CUDA 12.5.0) / windows-latest"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: Jimver/cuda-toolkit@v0.2.17
      id: cuda-toolkit
      with:
        cuda: '12.5.0'

    - name: Setup Python 3.12.5
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.5
        cache: 'pip'

    - name: Install PyTest
      run: |
        python -m pip install pytest pytest-github-actions-annotate-failures typing_extensions

    - name: Install NumPy
      run: |
        python -m pip install numpy scipy

    - name: Configure
      run: >
        cmake -S . -B build -DNB_TEST_CUDA=ON

    - name: Build C++
      run: cmake --build build -j 2 --config Release

    - name: Run tests
      run: >
        cd build;
        python3 -m pytest
